language: python
sudo: false
python:
  - "3.4"
  - "3.5"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pep8"
  - "pip install pylint"

script:
  - "coverage run --source=lalr setup.py test"
  - "pep8 lalr setup.py"
  - "pyflakes lalr setup.py"
  - "pylint -E lalr setup.py"

after_success:
  - "coveralls"
